### ISSUE TITLE
增加【随机】按钮

### ISSUE THREAD

**Issue by 17huiwei** [bilibili-tool/image-serenity#32]
这样能够大大增加可玩性

1）点击【随机】，进入“随机”页面，该页面有【刷新】和【返回】两个按钮
2）在随机页面中点【刷新】，可以不断产生新的随机页面
3）在随机页面中点【返回】，可以返回PAGE1

另，建议去掉顶部的【关于】和【主页】，可以把【关于】放到页面底部

供参考，多谢

**Comment by RyuSeiri** [comment]
@17huiwei 
已经对应了。

**Comment by 17huiwei** [comment]
十分感谢大神！！
