### ISSUE TITLE
UI美化建议

### ISSUE THREAD

**Issue by 17huiwei** [bilibili-tool/image-serenity#35]
针对顶部蓝色区块
1）稍微缩短蓝色区块的高度
2）将操作区域放到蓝色区块中，右侧或者中部
3）蓝色区块始终浮在顶部，方便操作，否则页面拉下去浏览，需要再拉回顶部操作翻页

暂时是一点愚见，哈哈，希望做得更好。

**Comment by RyuSeiri** [comment]
@17huiwei 
多谢提的建议，已经对应了。
